### PR TITLE
Feature: Replace followed threads links with my posts link

### PR DESCRIPTION
**Pull request by LemonIllusion**

### CODE REVIEW

**Comment by LemonIllusion** [comment]
The operation fails and an error is logged if user is not logged in. Is it possible to implement `isLoggedIn` in a reasonable way or should the error just be caught and suppressed?

**Comment by SimonAlling** [comment]
Regarding `isLoggedIn`: The other detectors in the `environment` module depend only on data available at `document-start`, namely `document.location.pathname`. For `isLoggedIn` to make sense, I think it should be implemented in the same way, i.e. not by looking at any page content.

And I hereby proudly present a solution:

```javascript
export function isLoggedIn(): boolean {
    return (document.head.textContent as string).includes(`'visitorType': 'member'`);
}
```

I have pushed the implementation above, so you should be able to use it if you pull that commit (d2865806570e1b2f5a2ce3a0439b8a1bacef0ad7).

**Comment by LemonIllusion** [comment]
I think I've gitted far beyond my proper understanding, but that should've been every change you requested and then some. Anything more to do?

**Comment by LemonIllusion** [comment]
Do you like the idea of using `${general.my_posts}` instead of writing out `Mina inlägg` in the setting label? It's less repetition, but would force a specific ordering of the text groups and possibly cause issues with circular dependencies if encouraged.

**Pull request merged**
